// Binary (WASI command) entry point for the zj-radar Zellij plugin. Zellij calls
// the wasm `_start` export (generated by register_plugin!'s fn main), so the
// artifact MUST be a binary crate. All logic lives in this crate's lib.

#[cfg(target_arch = "wasm32")]
use zellij_tile::prelude::*;

#[cfg(target_arch = "wasm32")]
zellij_tile::register_plugin!(zj_radar_plugin::State);

#[cfg(not(target_arch = "wasm32"))]
fn main() {}
